// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderTable = "order_table"

// OrderTable mapped from table <order_table>
type OrderTable struct {
	OrderID     int64 `gorm:"column:order_id;type:int;primaryKey;autoIncrement:true;comment:订单ID" json:"order_id"` // 订单ID
	UserID      int64 `gorm:"column:user_id;type:int;not null;comment:用户ID" json:"user_id"`                        // 用户ID
	ProductID   int64 `gorm:"column:product_id;type:int;not null;comment:商品ID" json:"product_id"`                  // 商品ID
	OrderTime   int64 `gorm:"column:order_time;type:int;not null;comment:下单时间" json:"order_time"`                  // 下单时间
	OrderStatus int64 `gorm:"column:order_status;type:int;not null;comment:订单状态" json:"order_status"`              // 订单状态
	OrderAmount int64 `gorm:"column:order_amount;type:int;not null;comment:下单数量" json:"order_amount"`              // 下单数量
}

// TableName OrderTable's table name
func (*OrderTable) TableName() string {
	return TableNameOrderTable
}
