// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ProductID     int64  `gorm:"column:product_id;type:int;primaryKey;autoIncrement:true;comment:商品ID" json:"product_id"` // 商品ID
	ProductName   string `gorm:"column:product_name;type:varchar(100);not null;comment:商品名称" json:"product_name"`         // 商品名称
	StockQuantity int64  `gorm:"column:stock_quantity;type:int;not null;comment:库存量" json:"stock_quantity"`               // 库存量
	Version       int64  `gorm:"column:version;type:int;not null;comment:版本号" json:"version"`                             // 版本号
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
